# Generated by Django 5.0.4 on 2024-04-18 18:14

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='نام مهارت')),
            ],
            options={
                'verbose_name_plural': 'مهارت های اعضا',
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='بذون نام', max_length=100, verbose_name='اسم کامل')),
                ('phone', models.CharField(default='-', max_length=11, verbose_name='للفن همراه')),
                ('picture', models.FileField(blank=True, null=True, upload_to='Profile/Picture/', verbose_name='تصویر')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرد مورد نظر')),
            ],
            options={
                'verbose_name_plural': 'پروفایل کاربری افراد',
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.CharField(max_length=120, verbose_name='معرفی نامه')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات درباره معرفی جامع عضو تیم')),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True, verbose_name='لینکدین')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='اینستاگرام')),
                ('skills', models.ManyToManyField(null=True, to='account.skills')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile', verbose_name='فرد')),
            ],
            options={
                'verbose_name_plural': 'اعضای تیم',
                'db_table': 'Team_Member',
            },
        ),
    ]
