# Generated by Django 5.0.4 on 2024-04-18 18:14

import ckeditor.fields
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Weblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='نام دسته بندی ')),
                ('slug', models.SlugField(help_text='این فیلد به طوری خودکار مقدار دهی میشود', unique=True, verbose_name='آدرس اینترنتی دسته بندی')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی پست های وبلاگ',
                'db_table': 'Category_Weblog',
            },
        ),
        migrations.CreateModel(
            name='Tags_Weblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, verbose_name='تگ برای پست های وبلاگ')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس اینترنتی برای تگ پست')),
            ],
            options={
                'verbose_name_plural': 'تگ های پست های وبسایت',
                'db_table': 'Tags_Weblog',
            },
        ),
        migrations.CreateModel(
            name='Post_Weblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='Post_Weblog/%Y/%m/%d', verbose_name='عکس مورد نظر')),
                ('post_name', models.CharField(max_length=100, verbose_name='عنوان پست ها')),
                ('slug', models.SlugField(help_text='به طور خودکار مقدار دهی میشود', verbose_name='آدرس اینترنتی پست')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن محتوای پست')),
                ('creation', django_jalali.db.models.jDateTimeField(verbose_name='انتخاب زمان ساخت')),
                ('time_duration', models.PositiveSmallIntegerField(verbose_name='زمان مورد نیاز برای مطالعه')),
                ('status', models.BooleanField(default=False, help_text='وضعیت انتشار خود را مشخص کنید    ', verbose_name='آیا منتشر شود ؟')),
                ('author', models.ForeignKey(help_text='انتخاب نویسنده', on_delete=django.db.models.deletion.CASCADE, related_name='post_weblog', to='account.profile', verbose_name='نویسنده')),
                ('category', models.ForeignKey(help_text='دسته بندی مرتبط به این پست را انتخاب کنید', on_delete=django.db.models.deletion.CASCADE, related_name='post_weblog', to='weblog.category_weblog', verbose_name='دسته بندی این پست')),
                ('tags', models.ManyToManyField(help_text='بیش از یکی هم میتوان انتخاب نمود', related_name='post_weblog', to='weblog.tags_weblog', verbose_name='تگ پست های وبسایت')),
            ],
            options={
                'verbose_name_plural': 'وبلاگ وبسایت',
                'db_table': 'Post_Weblog',
            },
        ),
        migrations.CreateModel(
            name='Comments_Weblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان کامنت')),
                ('text', models.TextField(verbose_name='متن کامنت ')),
                ('person', models.ForeignKey(help_text='کاربر مدنظر که لاگین کرده است میتواند کامنت را ثبت کند', on_delete=django.db.models.deletion.CASCADE, related_name='Comments_weblog', to='account.profile', verbose_name='انتخاب کاربر وبسایت')),
                ('post', models.ForeignKey(help_text='پست مورد نظر را انتخاب کنید', on_delete=django.db.models.deletion.CASCADE, to='weblog.post_weblog', verbose_name='انتخاب پست')),
            ],
            options={
                'verbose_name_plural': 'کامنت پست ها',
                'db_table': 'Comments',
                'ordering': ['-id'],
            },
        ),
    ]
