# Generated by Django 5.0.4 on 2024-04-18 18:14

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته بندی دوره های وبسایت')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس اینترنتی وبسایت')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی های دوره های وبسایت',
                'db_table': 'Course_Category',
            },
        ),
        migrations.CreateModel(
            name='Course_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تگ')),
                ('slug', models.SlugField(help_text='فیلد به طور خودکار مقدار دهی میشود', unique=True, verbose_name='آدرس اینترنتی تگ')),
                ('color', models.CharField(choices=[('bg-red-1', 'قرمز'), ('bg-white-1', 'سفید'), ('bg-dark-1', 'مشکی')], default='red', max_length=100, verbose_name='رنگ')),
            ],
            options={
                'verbose_name_plural': 'تگ های دوره های وبسایت',
                'db_table': 'Course_Tag',
            },
        ),
        migrations.CreateModel(
            name='Course_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='نام دوره')),
                ('picture', models.FileField(null=True, upload_to='Course_Information/%y/%m/%d', verbose_name='عکس اول')),
                ('intoduce_centense', models.CharField(max_length=100, null=True, verbose_name='توضیح خیلی مختصر')),
                ('course_description', ckeditor.fields.RichTextField(verbose_name='توضیحات دوره')),
                ('learning', ckeditor.fields.RichTextField(verbose_name='آنچه یادمیگیرید')),
                ('requirements', ckeditor.fields.RichTextField(verbose_name='پیش نیاز های دوره')),
                ('teacher_description', ckeditor.fields.RichTextField(verbose_name='توضیحات درباره مدرس ')),
                ('teacher_description_about_course', ckeditor.fields.RichTextField(null=True, verbose_name='توضیحات مدرس درباره دوره')),
                ('video', models.FileField(upload_to='Course_Information/<django.db.models.fields.CharField>/%y/%m/%d', verbose_name='ویدیو مقدمه انتشار دوره')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت دوره')),
                ('level', models.CharField(max_length=100, verbose_name='سطح دوره')),
                ('languages', models.CharField(max_length=100, verbose_name='زبان دوره')),
                ('exam', models.BooleanField(default=False, verbose_name='امتحان دارد')),
                ('duration', models.IntegerField(default=35, verbose_name='مدت دوره')),
                ('certificated', models.BooleanField(default=False, verbose_name='آیا مدرک دارد')),
                ('time', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, null=True, verbose_name='زمان ساخت')),
                ('update', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان آپدیت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course_category', verbose_name='نام دسته بندی')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_information', to='account.profile', verbose_name='مدرس')),
                ('tags', models.ManyToManyField(null=True, to='course.course_tag', verbose_name='تگ های دوره های وبسایت')),
            ],
            options={
                'verbose_name_plural': 'دوره های وبسایت',
                'db_table': 'Course_Information',
            },
        ),
        migrations.CreateModel(
            name='Course_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن کامنت برای دوره')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile', verbose_name='کاربر')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_comments', to='course.course_information', verbose_name='دوره آموزشی')),
            ],
            options={
                'verbose_name_plural': 'کامنت های دوره ها',
                'db_table': 'Course_Comments',
            },
        ),
    ]
