# Generated by Django 5.0.4 on 2024-04-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_information',
            name='video',
            field=models.FileField(upload_to='Course_Information/%y/%m/%d', verbose_name='ویدیو مقدمه انتشار دوره'),
        ),
    ]
