# Generated by Django 5.0.4 on 2024-04-18 18:14

import ckeditor.fields
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='Event/Pictures/%Y/%m/%d', verbose_name='تصویر سر تیتر برای سایت')),
                ('event_name', models.CharField(max_length=100, verbose_name='نام رویداد را وارد کنید')),
                ('location', models.CharField(max_length=100, verbose_name='محل برگزاری')),
                ('time', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ و زمان برگزاری')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('learning', ckeditor.fields.RichTextField(null=True, verbose_name='آنچه یادمیگیرید')),
                ('requirements', ckeditor.fields.RichTextField(null=True, verbose_name='پیشنیازهای رویداد')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت اصلی')),
                ('off', models.BooleanField(default=False, verbose_name='آیا تخفیف دارد')),
                ('price2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت تخفیف خورده')),
                ('Presentors', models.ManyToManyField(to='account.team_member', verbose_name='اراپه دهندگان')),
            ],
            options={
                'verbose_name_plural': 'رویداد های وبسایت',
                'db_table': 'Event_Information',
            },
        ),
        migrations.CreateModel(
            name='Event_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن کامنت برای رویداد')),
                ('time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to='account.profile', verbose_name='کاربر')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to='Event.event_information', verbose_name='رویداد')),
            ],
            options={
                'verbose_name_plural': 'کامنت های رویداد ها',
                'db_table': 'Event_Comment',
                'ordering': ['-id'],
            },
        ),
    ]
