# Generated by Django 5.0.4 on 2024-04-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان اسلایدر')),
                ('picture', models.FileField(upload_to='Silder/<django.db.models.fields.CharField>/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name_plural': 'تصاویر اسلایدر',
                'db_table': 'slider',
            },
        ),
    ]
