# Generated by Django 5.0.4 on 2024-04-18 19:17

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('no_response', 'بدون پاسخ'), ('in_response', 'در حال پاسخ'), ('out_response', 'پاسخ داده شده')], default='no_response', max_length=20, verbose_name='وضعیت')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'تیکت ارتباط با ما',
                'db_table': 'Contact_Us',
            },
        ),
        migrations.AlterField(
            model_name='slider',
            name='picture',
            field=models.FileField(upload_to='Silder/', verbose_name='تصویر'),
        ),
    ]
